version: "3.9"
services:

  postgres:
    image: postgres:14
    ports:
      - "PORT"
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "psql_data:/var/lib/postgresql/data"

  app:
    build:
      context: ./
      dockerfile: Dockerfile.deploy
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      db_host: postgres
    volumes:
      - "logs:/app/logs"

volumes:
  logs:
  psql_data: