FROM python:3.9

COPY . .
WORKDIR .



ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1


EXPOSE 8000

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install psycopg2-binary

# 
CMD ["python3", "src/db_controller/db_setup.py"]
CMD ["python3", "main.py"]