"""Create db

Revision ID: 4cfd5b81c22a
Revises: 88c35abc21e1
Create Date: 2023-08-13 14:58:09.041584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cfd5b81c22a'
down_revision: Union[str, None] = '88c35abc21e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('content_name', sa.String(length=255), nullable=False),
    sa.Column('content_value', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('content_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content')
    # ### end Alembic commands ###
