"""Create db

Revision ID: 6f80082cb638
Revises: 12e00f293bff
Create Date: 2023-08-13 15:00:41.260343

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f80082cb638"
down_revision: Union[str, None] = "12e00f293bff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content",
        sa.Column("content_name", sa.String(length=255), nullable=False),
        sa.Column("content_value", sa.String(length=1000), nullable=False),
        sa.PrimaryKeyConstraint("content_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("content")
    # ### end Alembic commands ###
